# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='identifier',
            new_name='ratings_notation',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='accepts_credit_cards',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address1',
            field=models.CharField(default='address1', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address2',
            field=models.CharField(default='address2', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='alcohol',
            field=models.CharField(default='No', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='attire',
            field=models.CharField(default='Casual', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='between',
            field=models.CharField(default='between', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(default='American (New)', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='claimed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dollar_signis',
            field=models.CharField(default='$$', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='fri',
            field=models.CharField(default='mon', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='fri1',
            field=models.CharField(default='mon', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='good_for_groups',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='good_for_kids',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hastv',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mon',
            field=models.CharField(default='mon', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mon1',
            field=models.CharField(default='mon', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='neighborhood',
            field=models.CharField(default='neighborhood', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='noise_level',
            field=models.CharField(default='Average', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='outdoor_seating',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='parking',
            field=models.CharField(default='Street', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(default='phone', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='prediction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ratings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='review',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sat',
            field=models.CharField(default='mon', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sat1',
            field=models.CharField(default='mon', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sun',
            field=models.CharField(default='mon', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sun1',
            field=models.CharField(default='mon', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='take_out',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='takes_reservations',
            field=models.CharField(default='Yes', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='thu',
            field=models.CharField(default='mon', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='thu1',
            field=models.CharField(default='mon', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tue',
            field=models.CharField(default='mon', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tue1',
            field=models.CharField(default='mon', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.CharField(default='website', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wed',
            field=models.CharField(default='mon', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wed1',
            field=models.CharField(default='mon', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wifi',
            field=models.CharField(default='Free', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='yelp_id',
            field=models.CharField(default='yelp_id', max_length=200),
        ),
    ]
