# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20171123_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='dollar_signis',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dollar_signs',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='accepts_credit_cards',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address1',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address2',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='alcohol',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='attire',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='between',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='fri',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='fri1',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='good_for_groups',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='good_for_kids',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='hastv',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='mon',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='mon1',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='neighborhood',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='noise_level',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='outdoor_seating',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='parking',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='ratings_notation',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='sat',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='sat1',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='sun',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='sun1',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='take_out',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='takes_reservations',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='thu',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='thu1',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tue',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tue1',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='wed',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='wed1',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='wifi',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='yelp_id',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
