# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20171124_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='between',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='neighborhood',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.CharField(default='', max_length=200),
        ),
    ]
