# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20171125_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='prediction',
            field=models.CharField(default='', max_length=200),
        ),
    ]
