# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20171208_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='prediction',
            field=models.IntegerField(default=0),
        ),
    ]
